apiVersion: apps/v1
kind: Deployment
metadata:
  name: emmanuel-services
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: emmanuel-services
  template:
    metadata:
      labels:
        app: emmanuel-services
    spec:
      containers:
        - name: emmanuel-web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80

